<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Logout</name>
   <tag></tag>
   <elementGuidId>5586719c-487f-4f75-ae1f-2f7d7297493d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#logout-href</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='logout-href']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Logout&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>abc071cf-6f1c-43ea-91a5-a3b369a643a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>logout-href</value>
      <webElementGuid>8e1378fd-be40-446f-a367-46ba5f30f2ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>logout-page.php?logout=1&amp;goto=clin-login-1.php</value>
      <webElementGuid>168152d2-bcf9-4ce3-91bf-8148adf5f1b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>logoutbtn</value>
      <webElementGuid>234690a0-e077-4050-ade9-4bc28847bffd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Logout</value>
      <webElementGuid>078af10c-5095-4389-a8e3-784398df261d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;logout-href&quot;)</value>
      <webElementGuid>c1963005-4392-498b-9d71-b3024607e73c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='logout-href']</value>
      <webElementGuid>4f542132-20ad-45c4-849d-2e121541c825</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='NavbarToggle']/div/a</value>
      <webElementGuid>4ffc4dd6-4c3c-4468-86bf-63a747323b09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Patient Dashboard'])[1]/preceding::a[1]</value>
      <webElementGuid>91ff2b1c-569f-4469-8ad3-c109d9585daa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Activity &amp; Billing'])[1]/preceding::a[1]</value>
      <webElementGuid>ee0a33dc-c698-46ef-8492-fafe9d87adcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Logout']/parent::*</value>
      <webElementGuid>e0c3d67a-53d4-4df4-9d4d-c9093a9e4d42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'logout-page.php?logout=1&amp;goto=clin-login-1.php')]</value>
      <webElementGuid>8b61114d-9e05-45f8-b0d7-eeea01cfdbfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>b891a7e8-aa14-48bd-a1c1-a118d1457c28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'logout-href' and @href = 'logout-page.php?logout=1&amp;goto=clin-login-1.php' and (text() = '  Logout' or . = '  Logout')]</value>
      <webElementGuid>9e50384a-a851-4ddb-aa98-6132252c52cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
