<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Verify (1)</name>
   <tag></tag>
   <elementGuidId>578416f7-76da-4f23-934e-f84b3b6aa5eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#verify-b</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='verify-b']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Verify&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ad9b1973-24da-4718-b562-c83986135079</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c581975e-f2c5-4a73-820d-304a1026fa3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>verify-b</value>
      <webElementGuid>108b08d1-7784-4475-ac2e-59080eaa2eb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>check_token(this); return(false);</value>
      <webElementGuid>a8d22f7b-9131-4e34-b9af-4749fe0eac54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Verify</value>
      <webElementGuid>5a1fef44-c963-4659-90d2-0817e0d391dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;verify-b&quot;)</value>
      <webElementGuid>242ced88-feac-4899-b2c1-4e86a3ce9c82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Login/iframe_concat(id(, , fancybox-frame17370179_b7bbe8</value>
      <webElementGuid>decadc49-6dec-4e5b-a15c-5b98b31eea95</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='verify-b']</value>
      <webElementGuid>2beb10c0-62f3-40d8-9365-bafcf1a8a521</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resend code'])[1]/following::button[1]</value>
      <webElementGuid>2a0a9577-9de6-4209-99e3-52139edc3cea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Two-Factor Authentication'])[1]/following::button[1]</value>
      <webElementGuid>ec62f814-f8ce-4772-9229-f22625b9bd0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Or, Enter a one-time code'])[1]/preceding::button[1]</value>
      <webElementGuid>5d1bf4b4-fe32-475c-86d1-1138e880e01e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Verify']/parent::*</value>
      <webElementGuid>b709a09a-31a1-4dfa-bad7-dab30d679083</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>dcd6a396-2c80-48bb-aaa0-f6a977cdd68b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'text' and @id = 'verify-b' and (text() = 'Verify' or . = 'Verify')]</value>
      <webElementGuid>24976fc0-cf94-4bbf-aa19-cd80837bfe7c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
