<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(id(, , fancybox-frame17370184_9ab702</name>
   <tag></tag>
   <elementGuidId>305ed15d-2b79-44aa-b59a-1649b06da9e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fancybox-frame1737018468222</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='fancybox-frame1737018468222']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;fancybox-frame1737018468222&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>8b47863d-3d42-428a-aba9-955c4f87a285</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fancybox-frame1737018468222</value>
      <webElementGuid>aaaff3b9-4f0b-4150-ba31-78c9b25374ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fancybox-frame1737018468222</value>
      <webElementGuid>9800c89a-aec0-4ef3-accd-3651271e47f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fancybox-iframe</value>
      <webElementGuid>6e9b3953-b288-48a6-a03c-61edb1c7f059</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5d1e4522-4914-4574-8383-81b978802b32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>vspace</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3c7d82a8-afaf-46b4-a833-473df36fa259</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>hspace</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a80e7e59-2c56-4c85-9bc7-4fd1fc148040</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>6bafbbf5-1349-4706-8299-45ff695263ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>verify-by-sms-this-user.php?local_day=16&amp;local_day_n=5&amp;local_month=1&amp;local_year=2025&amp;local_hour=11&amp;task=step1&amp;username=253z74Au&amp;password=WPjYj9%406</value>
      <webElementGuid>b356fe23-4c46-4bbc-99a8-7cf48694c5df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fancybox-frame1737018468222&quot;)</value>
      <webElementGuid>62a945a5-690d-4a59-8e32-a3ae326e1146</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='fancybox-frame1737018468222']</value>
      <webElementGuid>2befd011-e52c-4de9-a78e-df9dc6de719a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='goolgeLanding']/div[2]/div/div/div/div/iframe</value>
      <webElementGuid>992d2789-b61c-4275-b186-413c28501827</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>f9594186-61f8-410a-965b-74ea77256862</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'fancybox-frame1737018468222' and @name = 'fancybox-frame1737018468222' and @src = 'verify-by-sms-this-user.php?local_day=16&amp;local_day_n=5&amp;local_month=1&amp;local_year=2025&amp;local_hour=11&amp;task=step1&amp;username=253z74Au&amp;password=WPjYj9%406']</value>
      <webElementGuid>b6b91aef-6235-4f2f-ba78-b3e88d893a5c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
