<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(id(, , fancybox-frame17367462_965a30</name>
   <tag></tag>
   <elementGuidId>f11ca8cc-726f-40f4-87e0-44dd3edadd6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fancybox-frame1736746228369</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='fancybox-frame1736746228369']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;fancybox-frame1736746228369&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>0ebc84b2-874a-4a84-988d-1a2a1fd26c6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fancybox-frame1736746228369</value>
      <webElementGuid>83cd6be9-f7b9-4d17-b81f-75655be673ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fancybox-frame1736746228369</value>
      <webElementGuid>549529e7-26b0-4caa-bde6-6355ca4808f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fancybox-iframe</value>
      <webElementGuid>34ab6602-160e-4f04-b812-20c4ccc8fc01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>debc0d65-c955-489d-93f3-97c4dab58104</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>vspace</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f3882bac-ae41-4302-8751-803e255723f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>hspace</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>073443ee-8b18-4161-8813-fa6c74b8f4af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>c771ca79-e994-4282-9d7a-fed8cd14157c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>verify-by-sms-this-user.php?local_day=13&amp;local_day_n=2&amp;local_month=1&amp;local_year=2025&amp;local_hour=7&amp;task=step1&amp;username=253z74Au&amp;password=WPjYj9%406</value>
      <webElementGuid>423cc73c-ce37-4cb5-97d9-4c9f6cb3cbd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fancybox-frame1736746228369&quot;)</value>
      <webElementGuid>904ecc3a-0d39-4c1f-8cd8-27232fca7086</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='fancybox-frame1736746228369']</value>
      <webElementGuid>c3d67827-c3af-4daf-994b-5542285c57f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='goolgeLanding']/div[2]/div/div/div/div/iframe</value>
      <webElementGuid>f1f9165e-debb-4f00-a25a-c21c4cb03296</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>07a13266-a333-4bd7-8ca2-247304fef225</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'fancybox-frame1736746228369' and @name = 'fancybox-frame1736746228369' and @src = 'verify-by-sms-this-user.php?local_day=13&amp;local_day_n=2&amp;local_month=1&amp;local_year=2025&amp;local_hour=7&amp;task=step1&amp;username=253z74Au&amp;password=WPjYj9%406']</value>
      <webElementGuid>9d999c41-a69d-47c6-8709-5b4abadca985</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
