<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(id(, , fancybox-frame17370179_b7bbe8</name>
   <tag></tag>
   <elementGuidId>29cafb40-1335-446e-85a0-8f849daa92d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fancybox-frame1737017941898</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='fancybox-frame1737017941898']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;fancybox-frame1737017941898&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>913dced0-a413-4ed6-9bf0-9ca60ff037cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fancybox-frame1737017941898</value>
      <webElementGuid>69ac7446-0edd-4814-9334-d9334d5e3d5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fancybox-frame1737017941898</value>
      <webElementGuid>712da36a-dbdc-4110-99ee-9f81cd055e88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fancybox-iframe</value>
      <webElementGuid>4f42cdfa-f20c-416e-aaf9-a6cc3a1765b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6622c329-07b3-4a66-b363-05a1fcd4e0df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>vspace</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5ebaf744-3b78-4961-a92d-9481bc4f0919</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>hspace</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b4d02975-d7a7-4cc8-92e5-34403797d706</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>c9f4cf94-1fe2-49e6-8088-80a95b480bcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>verify-by-sms-this-user.php?local_day=16&amp;local_day_n=5&amp;local_month=1&amp;local_year=2025&amp;local_hour=10&amp;task=step1&amp;username=OmerQA2&amp;password=D5%24ZAjgD</value>
      <webElementGuid>cf666efc-8bba-4002-ae02-c3a15c4faa8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fancybox-frame1737017941898&quot;)</value>
      <webElementGuid>2fd66146-9aa4-4bb9-9c92-5d186a521e58</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='fancybox-frame1737017941898']</value>
      <webElementGuid>ee504518-8a72-46ff-98ef-2cff6d1449e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='goolgeLanding']/div[2]/div/div/div/div/iframe</value>
      <webElementGuid>d691a3ed-46f7-4f90-b59f-bcf138aa9aaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>eb8b2b28-81cf-4f17-95ab-8b330c41e82c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'fancybox-frame1737017941898' and @name = 'fancybox-frame1737017941898' and @src = 'verify-by-sms-this-user.php?local_day=16&amp;local_day_n=5&amp;local_month=1&amp;local_year=2025&amp;local_hour=10&amp;task=step1&amp;username=OmerQA2&amp;password=D5%24ZAjgD']</value>
      <webElementGuid>addc622d-c0b8-4920-be13-326c310aaa4c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
