<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Logout</name>
   <tag></tag>
   <elementGuidId>1744ca24-0519-4f9f-85ae-05f1e43ec204</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#logout-href</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='logout-href']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Logout&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a870026c-3184-43d3-bf8c-0907cc0212df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>logout-href</value>
      <webElementGuid>4cca4b06-66a3-470b-a205-310f449510f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>logout-page.php?logout=1&amp;goto=clin-login-1.php</value>
      <webElementGuid>bf33cc56-8418-4b52-9bdc-ce9bb3574321</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>logoutbtn</value>
      <webElementGuid>cf946936-af4b-4d65-864b-9d885c3ffeb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Logout</value>
      <webElementGuid>1d5930c9-3a69-4850-b107-77e27015f122</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;logout-href&quot;)</value>
      <webElementGuid>711fe0e3-bc1e-4169-8162-74b9f9ed52ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='logout-href']</value>
      <webElementGuid>98fcc493-07c0-4bcf-b4cb-1dd128517c35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='NavbarToggle']/div/a</value>
      <webElementGuid>08885263-8556-4028-ac2a-2551df366936</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Patient Dashboard'])[1]/preceding::a[1]</value>
      <webElementGuid>3e1aee48-295a-4a1e-9fa3-44987523a6a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Activity &amp; Billing'])[1]/preceding::a[1]</value>
      <webElementGuid>9de24cdd-c339-4ecc-ac08-47cdcb0399dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Logout']/parent::*</value>
      <webElementGuid>b005969b-737b-485c-aeec-25d9d6517b4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'logout-page.php?logout=1&amp;goto=clin-login-1.php')]</value>
      <webElementGuid>6f630b78-e086-40d8-802c-16cfc7f03462</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>de340734-d82b-4405-aff3-52c4be236716</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'logout-href' and @href = 'logout-page.php?logout=1&amp;goto=clin-login-1.php' and (text() = '  Logout' or . = '  Logout')]</value>
      <webElementGuid>2cc5ce5f-0f54-43d9-9bc7-e685102a737a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
