<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_View Diary</name>
   <tag></tag>
   <elementGuidId>e513dbea-6ab3-465a-8002-ac3061af34d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#diary-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='diary-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;View Diary&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>465eb960-c09f-4ae2-8a02-0ac9d35b0cf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>diary-button</value>
      <webElementGuid>8db1880f-74c5-497b-abd7-2f39cd1f5602</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>5f9a7a2b-4e4d-4f61-a091-20e1789492c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-main</value>
      <webElementGuid>205f65c2-4e10-4e28-9a80-fb28c43557ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View Diary</value>
      <webElementGuid>5c8591bf-41fd-4fae-9b3c-29e0cb0e35d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;diary-button&quot;)</value>
      <webElementGuid>e7290e92-43d7-4c85-82e0-f000c442739c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='diary-button']</value>
      <webElementGuid>8de6022a-92ee-4f62-b8fb-cd5cf86ce878</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab1-tab-pane']/div[2]/div[2]/div/a</value>
      <webElementGuid>54a63029-9e1a-435f-a6ad-880d22ce4585</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'View Diary')]</value>
      <webElementGuid>54b4d6b0-999e-426c-93c6-5af78f095616</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Patient Diary'])[1]/following::a[5]</value>
      <webElementGuid>d908e754-b772-4790-aaa8-8c180a83f19e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Other1'])[1]/following::a[7]</value>
      <webElementGuid>3a469e16-2eca-46e1-8e4d-ce111879cd80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Patient Actions'])[1]/preceding::a[1]</value>
      <webElementGuid>c15593bb-522a-4851-9c0d-81e559110dfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Patient Communication'])[1]/preceding::a[1]</value>
      <webElementGuid>098d9316-cb26-4b41-b585-f0849639b15a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View Diary']/parent::*</value>
      <webElementGuid>70b6c5ca-d0b4-4858-9f3a-5f843778c4fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[67]</value>
      <webElementGuid>4cb022e9-3a2e-4085-a60c-503aef10bb12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/a</value>
      <webElementGuid>da0456a4-9a76-4918-a91d-2974455793ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'diary-button' and @href = '#' and (text() = 'View Diary' or . = 'View Diary')]</value>
      <webElementGuid>d34e3315-71cc-4574-aad0-8b32a5d8c620</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
