<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_View Diary (1)</name>
   <tag></tag>
   <elementGuidId>184859d4-676a-4494-8360-7d53884a4e34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#diary-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='diary-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;View Diary&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>468f4095-a141-47ff-ad07-b12aa444f27e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>diary-button</value>
      <webElementGuid>1c4e9615-a9b6-469e-b5ce-ab8f8af6f41f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>a37d6057-69df-4bbc-a5fd-6e23b9a88ad7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-main</value>
      <webElementGuid>cbff9fd9-ae12-4f7e-bda2-df647e69db7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View Diary</value>
      <webElementGuid>c90a4a22-0bff-4487-92d5-04ac8f5a0079</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;diary-button&quot;)</value>
      <webElementGuid>d5ce317e-d93d-4827-88d1-9ae1484443fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='diary-button']</value>
      <webElementGuid>a5c1aaf5-78be-4273-bc08-0cb80f44fbbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab1-tab-pane']/div[2]/div[2]/div/a</value>
      <webElementGuid>0f8287ad-3d7c-4a4d-b33a-3e3fde065c4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'View Diary')]</value>
      <webElementGuid>a9bbf0c0-67bf-4830-aade-e043d9899ee6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Patient Diary'])[1]/following::a[5]</value>
      <webElementGuid>be454c70-711f-4e56-b4fd-17d199a08ca4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Other1'])[1]/following::a[7]</value>
      <webElementGuid>cb816451-783e-4d88-9509-3a0291dbfe13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Patient Actions'])[1]/preceding::a[1]</value>
      <webElementGuid>f76e6f0d-479d-473d-8e05-1a21aa32f6b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Patient Communication'])[1]/preceding::a[1]</value>
      <webElementGuid>eb162169-35b3-4f8f-bbce-d190588908f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View Diary']/parent::*</value>
      <webElementGuid>53924355-03b6-4a7b-83b2-34e922f2d4fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[67]</value>
      <webElementGuid>90790d38-2bc5-4aa3-a4c2-c89f3b135471</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/a</value>
      <webElementGuid>8945d73b-2845-4d24-ba60-8966865bad6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'diary-button' and @href = '#' and (text() = 'View Diary' or . = 'View Diary')]</value>
      <webElementGuid>91dbf733-30db-45a4-8182-391a0759f497</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
