<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_Assessments</name>
   <tag></tag>
   <elementGuidId>3380f12f-85d6-4206-aab4-57983e3dd60a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#assessments-button > h3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='assessments-button']/h3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Assessments&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>f37f1b2e-91c4-458f-be37-1f9d3c3a4f97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Assessments</value>
      <webElementGuid>cdf3a1e6-f66d-4ab5-8010-fb97734e1498</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;assessments-button&quot;)/h3[1]</value>
      <webElementGuid>e56a45d7-b77c-43e3-a4bd-f17b1b972104</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='assessments-button']/h3</value>
      <webElementGuid>6d9d0c4b-ae02-4248-b8a4-9623602840cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Patient Communication'])[1]/following::h3[1]</value>
      <webElementGuid>35b299a5-d4c8-49e3-b440-94c40bcfada2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Patient Actions'])[1]/following::h3[2]</value>
      <webElementGuid>41d7d524-0845-4437-b0d5-a9c615b88aac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exercising &amp; Lifestyle'])[1]/preceding::h3[1]</value>
      <webElementGuid>4fea5415-6d67-4707-ab9f-b049a16e7663</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Progressive Muscle Relaxation'])[1]/preceding::h3[2]</value>
      <webElementGuid>0ca93fa3-124b-437e-915c-275c979c726d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Assessments']/parent::*</value>
      <webElementGuid>181e0c50-9145-40e2-9577-1f5b4963f548</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/h3</value>
      <webElementGuid>c8472a81-1269-4e1b-bfaf-3c8aa1df55bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'Assessments' or . = 'Assessments')]</value>
      <webElementGuid>55cf6c8f-d362-4bb3-8234-01b816da2323</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
