<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(id(, , fancybox-frame17368518_ccff10</name>
   <tag></tag>
   <elementGuidId>95d97684-8eec-4ee7-ae64-dcaabf5f6aec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='fancybox-frame1736851866398']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fancybox-frame1736851866398</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;fancybox-frame1736851866398&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>dbea178f-4a56-4d8b-88be-05b5cb5a1a09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fancybox-frame1736851866398</value>
      <webElementGuid>ef132509-73f3-4e6c-9ffc-61aad079b9b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fancybox-frame1736851866398</value>
      <webElementGuid>3eea8365-b2ad-42c9-ba1f-0c736c866e9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fancybox-iframe</value>
      <webElementGuid>874da7ab-1454-46ea-a90b-efa5eff48d23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>babd86ba-e0c5-4e7f-89a8-68cdd6a593a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>vspace</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>46bfe9ce-549c-4b24-9920-00742fae4053</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>hspace</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ddc7f068-e455-4359-9bc8-0d31bdd4b98e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>54be742d-5e7f-4931-a7f7-de2b5a8c479e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../clin-view-user-relaxahead.php?u=2257&amp;c=10319&amp;t=1&amp;pt=Lisa Simpson</value>
      <webElementGuid>c94b6b94-08b4-4135-b2f5-a2a2039c21a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fancybox-frame1736851866398&quot;)</value>
      <webElementGuid>9b180104-5bb2-4f92-9214-6a86639c7d99</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='fancybox-frame1736851866398']</value>
      <webElementGuid>ce17ef21-e3b0-43b6-b47f-051e8ee3d7ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/iframe</value>
      <webElementGuid>d31920fc-6350-4c99-9827-2b90625ca1ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'fancybox-frame1736851866398' and @name = 'fancybox-frame1736851866398' and @src = '../clin-view-user-relaxahead.php?u=2257&amp;c=10319&amp;t=1&amp;pt=Lisa Simpson']</value>
      <webElementGuid>c74bda9a-0b5a-41f5-8ef0-452c6f084ab9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
