<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img (1)</name>
   <tag></tag>
   <elementGuidId>4d072196-5b98-4c7a-b842-379300bef219</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#logout-href > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='logout-href']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Logout&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>aaed871d-d5d3-4ac0-b0b2-81fd28cbb82c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../images2/head-icon4.svg</value>
      <webElementGuid>b15e6e95-dfde-4aa7-a50c-79947af9620a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;logout-href&quot;)/img[1]</value>
      <webElementGuid>652dad7b-bcde-4c1a-b00e-ebeaa4ea913b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='logout-href']/img</value>
      <webElementGuid>f33bf00a-52e6-4136-b980-55da3fbb4624</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a/img</value>
      <webElementGuid>3bf65672-e620-4c99-adba-07164d8c4e7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../images2/head-icon4.svg']</value>
      <webElementGuid>fa099004-8bdd-4258-9e2f-440710667f61</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
