<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_View Diary</name>
   <tag></tag>
   <elementGuidId>4d018138-b5e5-4b5b-939f-1f8e3de5130a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#diary-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='diary-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;View Diary&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9d6f7452-561b-4a13-94a4-751bfc0c3cc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>diary-button</value>
      <webElementGuid>26a30e93-2fe3-43af-8ed2-a91aeecb10c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>8b184ebc-2b05-40b6-a2ac-c818f0b55ed5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-main</value>
      <webElementGuid>214766fb-cea5-4789-853b-5c860a395c0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View Diary</value>
      <webElementGuid>aed19c15-cd44-4ab2-bed9-dd10a5b8ee2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;diary-button&quot;)</value>
      <webElementGuid>4bd8870b-730f-4c4c-b45e-9d2ed9ec10f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='diary-button']</value>
      <webElementGuid>70fd4da2-de0a-4aa0-981b-165c26fe593f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab1-tab-pane']/div[2]/div[2]/div/a</value>
      <webElementGuid>28829f50-c86a-4084-9d89-6f43596d50ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'View Diary')]</value>
      <webElementGuid>f3cbcdeb-9312-41a1-ac3c-74a60f8d969b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Patient Diary'])[1]/following::a[5]</value>
      <webElementGuid>dc2f7f20-3d6c-4f5b-8129-8d1059151ccb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Other1'])[1]/following::a[7]</value>
      <webElementGuid>f3e8bedd-a6ec-4169-a3a6-8d4a1dd1a11c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Patient Actions'])[1]/preceding::a[1]</value>
      <webElementGuid>1e8d9119-452b-466e-9c1a-959119fa31ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Patient Communication'])[1]/preceding::a[1]</value>
      <webElementGuid>a692ec12-867f-4082-acc1-c7349a799b71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View Diary']/parent::*</value>
      <webElementGuid>f719ded9-91f7-47b6-8ad0-4f8e8ae6f0c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[67]</value>
      <webElementGuid>b3b57eca-c2e4-4b80-9af0-806d8731ca33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/a</value>
      <webElementGuid>1ae6552c-bad5-4f88-9790-9f4cec47a34b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'diary-button' and @href = '#' and (text() = 'View Diary' or . = 'View Diary')]</value>
      <webElementGuid>e974e0eb-13a6-479f-a085-68df1e1a923e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
