<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Change</name>
   <tag></tag>
   <elementGuidId>ff5e97a5-31e7-406b-8e43-5fb791adc60f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='patients-list-v2']/li/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Change&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7480d1d5-4c0a-46d8-967b-e42166d6deec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Change</value>
      <webElementGuid>a968c5ec-3a31-4e61-9ff7-60f079b11580</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;patients-list-v2&quot;)/li[1]/a[1]/span[1]</value>
      <webElementGuid>61921c54-11f7-4857-a5ab-c9d5d7ad63e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='patients-list-v2']/li/a/span</value>
      <webElementGuid>1d93ad55-ecbc-40ae-a92e-49e701de79c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bart Simpson'])[1]/following::span[1]</value>
      <webElementGuid>b9e78eeb-3883-46fe-9a0a-6f95206b2978</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort by'])[1]/following::span[2]</value>
      <webElementGuid>dad56bec-b722-488e-9c01-056606751325</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lisa Simpson'])[1]/preceding::span[1]</value>
      <webElementGuid>060f54fa-fd84-4ea3-bc0d-4d566f5c2323</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change'])[2]/preceding::span[2]</value>
      <webElementGuid>b2bad1d2-55fc-4c7c-828a-bd4606258b19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Change']/parent::*</value>
      <webElementGuid>bd258f9f-ec9d-4120-9bfe-25241ba40e06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/span</value>
      <webElementGuid>6c4af03e-776c-4402-bb9d-74d0c08f51ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Change' or . = 'Change')]</value>
      <webElementGuid>3280cebe-674c-479d-82d5-7a563e7817ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
